### ISSUE TITLE
[Bug]: tracker filter is messy

### ISSUE THREAD

**Issue by seeson** [VueTorrent/VueTorrent#1817]
### Bug description

tracker filter is not working properly, it displays all the tracker URL details

### Expectations

display the website name only.

### Relevant debug informations

![1722543212398](https://github.com/user-attachments/assets/68060eca-3231-458c-893f-5e0299453086)

### Steps to reproduce

1. ...
2. ...
...

### How did you install VueTorrent?

Downloaded from GitHub releases

### Environment description

```plain text
Device type and name: synology
OS: 

PWA: No
Running inside a container: Yes
```

### qBittorrent version

4.6.5

### VueTorrent version

2.11.1

### Agreements

- [X] The bug still occurs on the nightly build
- [X] The bug still occurs on the latest version of qBittorrent
- [X] A similar issue doesn't already exist
