### ISSUE TITLE
[Bug]: Tracker Filter Functionality Issue

### ISSUE THREAD

**Issue by swwrww** [VueTorrent/VueTorrent#1917]
### Bug description

 The tracker filter feature in Vuetorrent is not functioning as expected. When selecting the "untracked" option, it incorrectly filters and displays multiple seeds with trackers marked as "working."

### Expectations

Only seeds without any trackers should be displayed.

### Relevant debug informations

![image](https://github.com/user-attachments/assets/633c74c1-684a-4a78-9972-2258d9dfc3fc)

### Steps to reproduce

1. Open Vuetorrent UI.
2. Navigate to the tracker filter options.
3. Select "untracked."
4. Observe the displayed seeds.

### How did you install VueTorrent?

Downloaded from GitHub releases

### Environment description

```plain text
Device type: Desktop
OS: archlinux
Browser Chrome 129.0.6668.58 
Running inside a container: No
```

### qBittorrent version

4.6.7

### VueTorrent version

2.13.1

### Agreements

- [X] The bug still occurs on the nightly build
- [X] The bug still occurs on the latest version of qBittorrent
- [X] A similar issue doesn't already exist
- [X] I checked the DevTools and included any errors that may show up

**Comment by Larsluph** [comment]
Probably the same root cause as #1929 if the bug has been resolved

**Comment by swwrww** [comment]
> Probably the same root cause as #1929 if the bug has been resolved


The issue hasn't been resolved, and now the situation is the opposite. Some trackers that are not in a working state can no longer be filtered out.

**Comment by Larsluph** [comment]
Then why did you close the issue? Are you able to reproduce this in the OG webui?

**Comment by swwrww** [comment]
> Then why did you close the issue? Are you able to reproduce this in the OG webui?

I'm sorry for not being precise. When I updated to the latest version and all the trackers for my torrents were in a working state, I filtered for untracked torrents and didn't find any, so I assumed the bug was fixed. However, after restarting my qBittorrent today, many trackers were not working properly, yet the 'untracked' filter still couldn't filter out any torrents.

Sorry, my English is not very good, so I can only rely on GPT to translate it for me before sending it out.

**Comment by swwrww** [comment]
![image](https://github.com/user-attachments/assets/ba921534-fc46-4032-a2c5-df6ef2dd1d19)
![image](https://github.com/user-attachments/assets/abaaa175-622e-4cc1-98af-f59c518fc24a)

**Comment by Larsluph** [comment]
Oh I think I know why. There is a difference between Untracked torrent and torrents with failing trackers.

Vuetorrent only checks for untracked torrents as the name states. I'm not sure how to obtain tracker status for multiple torrents.

**Comment by Larsluph** [comment]
I looked up the OG webui code and it looks like they don't make any difference either, they can only filter torrents with trackers and torrents without, which is exactly what we do.

Based on the data the API provides, we can't do much better unfortunately...

**Comment by terrytw** [comment]
@Larsluph It seems that OG WEBUI added this:
https://github.com/qbittorrent/qBittorrent/pull/19672

**Comment by Larsluph** [comment]
@terrytw What you mentioned is for the GUI, not the WebUI. There isn't any alternative available through the Web API...

**Comment by terrytw** [comment]
OK my bad...

**Comment by Larsluph** [comment]
This only works for a single torrent. There isn't any endpoint for fetching these for all torrents at once.

**Comment by terrytw** [comment]
I see, you must be talking about this:
https://github.com/qbittorrent/qBittorrent/wiki/WebUI-API-(qBittorrent-4.1)#get-torrent-list

How about this, get all torrent, and filter them by `tracker` property, as described:
<html>
<body>

tracker | string | The first tracker with working status. Returns empty string if no tracker is working.



</body>
</html>
When it returns empty string, it means we have a torrent without functioning tracker.

**Comment by Larsluph** [comment]
I think I found the issue here, ATM we take the list of trackers from qbittorrent and form a list of trackers associated with each torrent. It looks like this data doesn't take status into account.

> tracker | string | The first tracker with working status. Returns empty string if no tracker is working.

I updated the matcher to use the field mentioned, we'll see how it goes.
